on:
  workflow_call:
    secrets:
      JF_ACCESS_TOKEN:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NPM cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Authenticate repository
        env:
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        run: |
          echo "registry=https://fsaiartifact.jfrog.io/artifactory/api/npm/fsai-private-npm-AUS-virtual/" > .npmrc
          echo "//fsaiartifact.jfrog.io/artifactory/api/npm/fsai-private-npm-AUS-virtual/:_authToken=${JF_ACCESS_TOKEN}" >> .npmrc
          echo "always-auth=true" >> .npmrc
          echo "NPM_CONFIG_USERCONFIG=$PWD/.npmrc" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm clean-install --prefer-offline --no-audit --no-fund
      - name: Install OS tool
        run: npm install --global platform-os-tool --no-audit --no-fund
      - name: Run project checks
        run: npm run check
      - name: Package with OS tool
        run: os package-tool .
